### ISSUE TITLE
psci crashes due to a syntax error

### ISSUE THREAD

**Issue by ashgaliyev** [purescript/purescript-eff#15]
When I run pulp psci
It falls with 
```
Error found:
at /Users/andreyash/Development/purescript-test
/bower_components/purescript-eff/src
/Control/Monad/Eff/Class.purs line 19, column 33 - line 19, column 33

  Unable to parse module:
  unexpected |
  expecting no indentation or end of input
```
When I deleted ```| m -> eff``` from 19 line the error was gone

I do not understand why this code is required for

**Comment by paf31** [comment]
The code is a _functional dependency_. I recently wrote about them in the book, but they are available in 0.10.1. You should upgrade your compiler or downgrade your libraries using Bower.
