### ISSUE TITLE
Ideas for fewer transitive dependencies?

### ISSUE THREAD

**Issue by chexxor** [purescript/purescript-eff#33]
I discovered just now that Eff now has a transitive dependency on ps-control and ps-invariant now, as those are dependencies of ps-monoid, added recently by https://github.com/purescript/purescript-eff/pull/32.

A bit disappointing, but just an observation. Take a look at the packages required to do main = log "Hello sailor":

https://github.com/chexxor/documentation/blob/ad508b5f7c49b07542a69b88af36218717ab8e31/guides/Dependency-Management/Git.purs

Gotta pull in purescript-control and those fun things, just for "Hello World"!

Again, not a problem, really, just a _bit_ disappointing that purescript-control needs to be installed to do the Hello World program.

Just opening an issue to collect suggestions for improving this.

**Comment by hdgarrood** [comment]
Sorry, I don't think this is a worthwhile endeavour. The vast majority of packages depend on control and invariant anyway, and they're both very small. To me, the benefit having the `Monoid Eff` instance clearly outweighs any drawback of these dependencies.

**Comment by chexxor** [comment]
Can I add a link to a smaller version of effectively to this repo's readme?

On Feb 28, 2018 2:36 PM, "Harry Garrood" <notifications@github.com> wrote:

Closed #33 <https://github.com/purescript/purescript-eff/issues/33>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/purescript/purescript-eff/issues/33#event-1497619535>,
or mute the thread
