### ISSUE TITLE
Move to purescript-deprecated?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-eff#35]
I see this library wasn't updated and isn't in the 0.12.0 package set. Are there any plans to update it, or should it be deprecated?

**Comment by garyb** [comment]
I wasn't planning to update it, but hadn't planned on not updating it either, if that makes sense. :smile:

I'm not sure what's best, whether it might be confusing having it kicking around still, given core uses `-effect` for everything now.

**Comment by hdgarrood** [comment]
The policy, as far as I'm aware, is that everything under the purescript org counts as a core library, and that core libraries are always maintained and updated for new releases. If we're not planning to maintain it at the level of other core libraries (which is fine by me) then I think it should move it out of this org. Moving to purescript-deprecated with a notice of "we aren't maintaining this any more but if you want to pick it up, here it is" in the README would be a good option, I think.

**Comment by AesaKamar** [comment]
Yeah, this was kind of confusing for me as a beginner jumping right into the language.

**Comment by fredefox** [comment]
FWIW I just jumped into Chapter 8 of PureScript By Example (on the `Eff` monad). Spent a bit of time on trying to resolve some conflicting dependencies. It would've been nice if there was a deprecation warning (or similar) on the module documentation for `Eff`.

**Comment by garyb** [comment]
I've moved it now and added a deprecation notice pointing people to `Effect` (or `Run`). Sorry to those who lost time to it!
