### ISSUE TITLE
add unsafePerformEff to .Unsafe?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-eff#8]
It's not obvious at first that it's possible to implement `unsafePerformEff :: forall e a. Eff e a -> a` in terms of the functions this library already exports without using the FFI.

I've seen a few people implementing their own `unsafePerformEff` via the FFI, which probably doesn't matter very much, although it does have a potential of causing pain with backends other than JS.

Perhaps we should add `unsafePerformEff` to `Control.Monad.Eff.Unsafe` to prevent this from happening so often?

**Comment by paf31** [comment]
:+1:

**Comment by garyb** [comment]
:+1:
